from pathlib import Path
from html.parser import HTMLParser
import json

# ==========================================
# 基础路径配置
# ==========================================
ROOT_DIR = Path(__file__).resolve().parent
DATABASE_DIR = ROOT_DIR / "database"
OUTPUT_FILE = ROOT_DIR / "js" / "config" / "pages" / "databar.js"


# ==========================================
# HTML Metadata Parser
# ==========================================
class MetadataParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.metadata = {}

    def handle_starttag(self, tag, attrs):
        if tag.lower() == "meta":
            attr_dict = {k.lower(): v.strip() for k, v in attrs if v}
            name = attr_dict.get("name")
            content = attr_dict.get("content")
            if name and content:
                self.metadata[name.lower()] = content


# ==========================================
# 工具函数
# ==========================================
def slug_to_title(slug: str) -> str:
    """将 slug 转换为首字母大写的标题"""
    return " ".join(word.capitalize() for word in slug.split("-"))


def read_metadata(html_file: Path) -> dict:
    parser = MetadataParser()
    try:
        parser.feed(html_file.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"⚠️ Failed to read: {html_file}\n   {e}")
    return parser.metadata


def read_article(html_file: Path) -> dict:
    metadata = read_metadata(html_file)
    return {
        "id": html_file.stem,
        "title": slug_to_title(html_file.stem),
        "date": metadata.get("date", ""),
        "tag": slug_to_title(html_file.parent.name),
        "url": metadata.get("url", ""),
        "summary": metadata.get("summary", "")
    }


# ==========================================
# 构建 Database
# ==========================================
def build_database() -> dict | None:
    if not DATABASE_DIR.exists():
        print(f"❌ Database directory not found:\n   {DATABASE_DIR}")
        return None

    categories = []
    
    # 使用 sorted 配合生成器，筛选出子目录
    for category_dir in sorted(p for p in DATABASE_DIR.iterdir() if p.is_dir()):
        # 使用 .glob() 代替手动判断文件后缀，代码更简洁
        articles = [
            read_article(article_file)
            for article_file in sorted(category_dir.glob("*.html"))
        ]

        categories.append({
            "name": slug_to_title(category_dir.name),
            "articles": articles
        })

    return {
        "database": {
            "title": "Database",
            "categories": categories
        }
    }


# ==========================================
# 生成 JavaScript 并写入
# ==========================================
def generate_js(data: dict) -> str:
    database_json = json.dumps(data, ensure_ascii=False, indent=4)
    return f"""// ==========================================
// 文章数据库配置 / Article database configuration
// ==========================================
// 此文件由 buildDatabar.py 自动生成，请勿手动修改。
// This file is automatically generated by buildDatabar.py.

window.DATABAR_CONFIG = {database_json};
"""


def write_output(content: str):
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(content, encoding="utf-8")


# ==========================================
# Main
# ==========================================
def main():
    print("🔨 Building Databar...")

    data = build_database()
    if not data:
        return

    write_output(generate_js(data))

    categories = data["database"]["categories"]
    category_count = len(categories)
    article_count = sum(len(cat["articles"]) for cat in categories)

    print("✅ Databar generated successfully.")
    print(f"   Categories: {category_count}")
    print(f"   Articles:   {article_count}")
    print(f"   Output:     {OUTPUT_FILE.relative_to(ROOT_DIR)}")


if __name__ == "__main__":
    main()